name: noteep
description: "A digital notebook of tasks."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.2
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  ming_cute_icons: ^0.0.7
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  logger: ^2.5.0
  shared_preferences: ^2.3.4
  provider: ^6.1.2
  intl: ^0.19.0
  intl_utils: ^2.8.7
  flutter_localizations:
    sdk: flutter
  toastification: ^2.3.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  share_plus: ^10.1.3
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo_icon.png"
